version: "3.9"

services:
  rabbitmq:
    image: rabbitmq:3.8-management-alpine
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    healthcheck:
      test: rabbitmq-diagnostics -q status
      interval: 2s
      timeout: 2s
      retries: 3
      start_period: 10s
    restart: always
    volumes:
      - rabbitmq:/var/lib/rabbitmq/
      - rabbitmq:/var/log/rabbitmq/
    networks:
      - rabbitmq_go_net

  gses:
    container_name: gses
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - .env
    ports:
      - 3000:3000
    command:
      - /bin/sh
      - -c
      - |
        npm run build && npm run start
    restart: on-failure
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - rabbitmq_go_net

networks:
  rabbitmq_go_net:
    driver: bridge

volumes:
  rabbitmq:
    driver: local
